
name: Build and deploy Python app to streamlit - PredictionProba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Create and start virtual environment
        run: |
                python -m venv venv
                source venv/bin/activate

      - name: Install dependencies
      run: pip install -r requirements.txt

      - name: Run Test unitaire API
        run: pytest ./test/test_api.py
  
    # deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # environment:
    #   name: 'Production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # steps:
    #   - name: Download artifact from build job
    #     uses: actions/download-artifact@v2
    #     with:
    #       name: python-app
    #       path: .
          
    #   - name: 'Deploy to Azure Web App'
    #     uses: azure/webapps-deploy@v2
    #     id: deploy-to-webapp
    #     with:
    #       app-name: 'PredictionProba'
    #       slot-name: 'Production'
    #       publish-profile: streamlit deploy --token ${{ secrets.STREAMLIT_123456789 }} 
    #       {{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A136748363C64F43B5245DA7ED3B32B3 }}